chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

firstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('like.urls')),
    path('account/', include('account.urls')),
    path('email/', include('emailapp.urls')),
    path('chat/', include('chat.urls')),
    path('weather/', include('weather.urls')),
    path('star/', include('star.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

like/urls.py
from django.urls import path
from .views import PhotoList, PhotoCreate, PhotoDetail, PhotoUpdate, delete
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from . import views

app_name = "like" #다른 앱들과 urlpattern이 겹치는것을 방지하기위해 사용
urlpatterns = [
    path('', PhotoList.as_view(), name="index"), #클래스형 view
    path('create/', PhotoCreate.as_view(), name="create"),
    path('delete/<int:post_id>', views.delete, name="delete"),
    path('update/<int:pk>', PhotoUpdate.as_view(), name="update"),
    path('detail/<int:pk>', PhotoDetail.as_view(), name="detail"),
    path('like/', views.post_likes, name="post_likes"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

like/models.py
from django.db import models
from django.contrib.auth.models import User
#장고에서 구현해주고 있는 user불러오기
from django.urls import reverse
from django.conf import settings


class Photo(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
  #Photo model을 user에 foreignkey로 연결 models.CASCADE : 외래키도 함께 삭제
  text = models.TextField(blank = True)
  image = models.ImageField(upload_to = 'timeline_photo/%Y/%m/%d')
  #ImageField :  FileField를 상속받은 필드이며, Pillow라는 따로 install 받은 이미지 처리 라이브러리를 통해서 이미지 정보를 획득.
  #*FileField : File Storage API를 통해 파일을 저장하며, django-storages를 통해 확장이 가능
  #upload_to : MEDIA_ROOT 하위에 저장할 파일,경로명 설정
  #timeline_photo폴더에 연도, 월, 일을 만들어서 사진을 저장 -> 년원일을 지정하면 파일끼리 충돌 방지 가능
  created = models.DateTimeField(auto_now_add = True) #최초 DB입력시간
  updated = models.DateTimeField(auto_now = True) #변화가 있을 때 즉, 수정했을 때의 시각
  #좋아요
  like = models.ManyToManyField(User, related_name='like', blank = True)

  def __str__(self):
    return self.text

  class Meta:
    ordering = ['-created']

  #상세페이지로 이동하도록 absolute_url 설정 
  def get_absolute_url(self):
    return reverse('like:detail', args=[self.id]) #이후에 views에서 return super가 나오게 되면 자동적으로 absolute_url 이 실행

like/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib import messages
#django.views.generic
#제네릭뷰란 장고에서 기본적으로 제공하고 있는 뷰의 형태로, 개발할 때 자주 등장하는 내용을 모아놓은 뷰를 뜻한다. 개발의 속도를 더욱 빠르게 만들어주어 편리하게 개발할 수 있다는 장점이 있다.
#종류도 다양함 - 찾아보는것 추천!
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.detail import DetailView
from .models import Photo
import json

class PhotoList(ListView):
  model = Photo
  template_name_suffix = '_list' #사용하는 탬플릿 명을 '모델명_list.html'로 바꾼다는 의미.
                                #해당 기능 완료후 연결될 템플릿 이름

class PhotoCreate(CreateView):
  model = Photo
  fields = ['text', 'image'] #생성시 채워야할 필드
  template_name_suffix = '_create'
  success_url = '/' #성공후 메인 페이지로 돌아가도록 연결(이후 url로 연결)

  #생성시 user 확인
  def form_valid(self, form):
    form.instance.author_id = self.request.user.id
    if form.is_valid():
      form.instance.save()
      return redirect('/')
    else:
      return self.render_to_response({'form':form}) 

class PhotoUpdate(UpdateView):
  model = Photo
  fields = ['text', 'image']
  template_name_suffix = '_update'
  #success_url = '/'

  def dispatch(self, request, *args, **kwargs): #사용자가 접속하였을 때 get이냐, post이냐를 결정하고 분기를 자동으로 해줌
    object = self.get_object()
    if object.author != request.user:
      messages.warning(request, '수정할 권한이 없습니다.')
      return HttpResponseRedirect('/')
    else:
      #super을 써줘서 원래 Updateview가 실행되도록 해주며 super을 쓰게 되면 실행시 absolute_url로 자동적으로 이동한다. (단 success url이 설정되어 있으면 우선시 된다.)
      return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)

def delete(request, post_id):
    post = Photo.objects.get(id=post_id)
    post.delete()
    return redirect('/')

class PhotoDetail(DetailView):
  model = Photo
  template_name_sufffix = '_detail'


def post_likes(request): 
  if request.is_ajax(): #ajax 방식일 때 아래 코드 실행
    blog_id = request.GET['blog_id'] #좋아요를 누른 게시물id (blog_id)가지고 오기
    post = Photo.objects.get(id=blog_id) 
    
    user = request.user #request.user : 현재 로그인한 유저
    if post.like.filter(id = user.id).exists(): #이미 좋아요를 누른 유저일 때
      post.like.remove(user) #like field에 현재 유저 추가
      message = "좋아요 취소" #화면에 띄울 메세지
    else: #좋아요를 누르지 않은 유저일 때
      post.like.add(user) #like field에 현재 유저 삭제
      message = "좋아요" #화면에 띄울 메세지
      #post.like.count() : 게시물이 받은 좋아요 수  
  context = {
    'like_count' : post.like.count(),
    'message':message,
  }
  return HttpResponse(json.dumps(context), content_type='application/json')   

like/templates/like/photo_create.html
<form action="" method=post enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

like/templates/like/photo_delete.html
<div class="alert alert-primary" role="alert">
  정말로 지우실건가요?
</div>
<form action="" method=post>
  {% csrf_token %}
  <input type="submit" class="btn btn-primary" value="Delete">
</form>

like/templates/like/photo_detail.html
{% load static %}
<head>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.js"
      integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
  <style>
    .heart {
      width:15px;
      height:15px;
    }
    button{
      padding: 0;
      border: none;
      background: none;
    }
    a{
      color:darkblue
    }
    img{
      display: block;
      margin-left: auto;
      margin-right: auto;
    }
  </style>
</head>
<div class="card mb-3">
  <img src="{{ object.image.url }}" height=200 width=200 class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ object.author }}</h5>
    <p class="card-text">{{ object.text }}</p>
    {% if user == object.author %}
    <div class="card-body">
      <a href="{% url 'like:update' object.id %}" class="card-link">수정</a>
      <a href="{% url 'like:delete' object.id %}" class="card-link">삭제</a>
    </div>
    {% endif %}
    {% if user.is_authenticated %}
  <button id="{{object.id}}" onclick="post_like(this.id)">
    {%if request.user in object.like.all%}
    <!-- 로그인 한 유저가 좋아요를 누른 유저일때  -->
    <img class="heart" id="heart{{object.id}}" src="{% static 'heart.png' %}" alt="full_heart">
    {%else%}
    <!-- 로그인 한 유저가 좋아요를 누른 유저가 아닐 때  -->
    <img class="heart" id="heart{{object.id}}" src="{% static 'empty_heart.png' %}" alt="empty_heart">
    {%endif%}
  </button>
  {% else %}
  <button id="{{object.id}}" onclick="alert('로그인이 필요합니다')">
    <img class="heart" id="heart" src="{% static 'empty_heart.png' %}" alt="empty_heart">
  </button>
  {% endif %} 
    <span id="like_count{{object.id}}">{{ object.like.count }}</span>
    <!-- <p id="like-user-{{post.id}}">
    {% for like_user in post.like_user_set.all %}
      {{ like_user.profile.nickname }}
    {% endfor %}
    </p> -->
</div>
<script type="text/javascript">
  function post_like(o_id) {
    $.ajax({
      type: "GET",
      url: "{% url 'like:post_likes' %}", // data를 전송할 url 입니다.
      data: {
        'blog_id': o_id
      }, // post_id 라는 name으로 id 값 전송
      dataType: "json",
      success: function (response) { // ajax 통신이 정상적으로 완료되었을 때
        $('#like_count'+o_id).html(response.like_count) //id가 like_count의 내용을 전송받은 좋아요 수로 바꾼다
        //$('#message').html(response.message) //id가 message의 내용을 전송받은 message로 바꾼다
        //$('.toast').fadeIn(400).delay(100).fadeOut(400)
          if (response.message == "좋아요")
        //좋아요 눌렀을 때 
        {
          $('#heart'+o_id).attr("src", "{% static 'heart.png' %}")
        } else if (response.message == "좋아요 취소")
        //좋아요 상태에서 다시 눌렀을 때 
        {
          $('#heart'+o_id).attr("src", "{% static 'empty_heart.png' %}")
        }
      }
    })
  }
  </script>

like/templates/like/photo_list.html
{% extends 'like_base.html' %}
{% load static %}
{% block content %}
<head>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.js"
      integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
  <style>
    .heart {
      width:20px;
      height:20px;
    }
    .flex_item{
      margin-top: 40px;
      max-width: 400px;
    }
    button{
      padding: 0;
      border: none;
      background: none;
    }
    a{
      color:darkblue
    }
    .card-title, .text-muted{
      font-size: 10px;
      color:darkgray;
    }
    .card-title{
      float: right;
    }
    img{
      display: block;
      margin-left: auto;
      margin-right: auto;
    }
  </style>
</head>

{% for post in object_list %}
<div class="flex_item">
  <img src="{{ post.image.url }}"alt="..."><br>
  <small class="card-title">{{ post.author }}님의 게시글</small><br>
    <p class="card-text">{{ post.text }}</p>
  <div class="card-body">
    <a href="{% url 'like:detail' post.id %}" class="card-link">💬</a>
    {% if user == post.author %}
    <a href="{% url 'like:update' post.id %}" class="card-link">수정</a>
    <a href="{% url 'like:delete' post.id %}" class="card-link">삭제</a>
    {% endif %}    
    <a href="{% url 'like:detail' post.id %}" class="card-link">자세히</a>
  {% if user.is_authenticated %}
  <button id="{{post.id}}" onclick="post_like(this.id)">
    {%if request.user in post.like.all%}
    <!-- 로그인 한 유저가 좋아요를 누른 유저일때  -->
    <img class="heart" id="heart{{post.id}}" src="{% static 'heart.png' %}" alt="full_heart">
    {%else%}
    <!-- 로그인 한 유저가 좋아요를 누른 유저가 아닐 때  -->
    <img class="heart" id="heart{{post.id}}" src="{% static 'empty_heart.png' %}" alt="empty_heart">
    {%endif%}
  </button>
  {% else %}
  <button id="{{post.id}}" onclick="alert('로그인이 필요합니다')">
    <img class="heart" id="heart" src="{% static 'empty_heart.png' %}" alt="empty_heart">
  </button>
  {% endif %} 
  <span id="like_count{{post.id}}">{{post.like.count}}</span>
  <br>
  <small class="text-muted">생성일 : {{ post.created }}</small><br>
  <small class="text-muted">수정일 : {{ post.updated }}</small><br>
  </div> 
</div>
  {% endfor %}  
<script type="text/javascript">
  function post_like(p_id) {
    $.ajax({
      type: "GET",
      url: "{% url 'like:post_likes' %}", // data를 전송할 url 입니다.
      data: {
        'blog_id': p_id
      }, // post_id 라는 name으로 id 값 전송
      dataType: "json",
      success: function (response) { // ajax 통신이 정상적으로 완료되었을 때
        $('#like_count'+p_id).html(response.like_count) //id가 like_count의 내용을 전송받은 좋아요 수로 바꾼다
        //$('#message').html(response.message) //id가 message의 내용을 전송받은 message로 바꾼다
        //$('.toast').fadeIn(400).delay(100).fadeOut(400)
          if (response.message == "좋아요")
        //좋아요 눌렀을 때 
        {
          $('#heart'+p_id).attr("src", "{% static 'heart.png' %}")
        } else if (response.message == "좋아요 취소")
        //좋아요 상태에서 다시 눌렀을 때 
        {
          $('#heart'+p_id).attr("src", "{% static 'empty_heart.png' %}")
        }
      }
    })
  }
  </script>
{% endblock %}

like/templates/like/photo_update.html
<form action="" method=post>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>